### ISSUE TITLE
Easier sleeping blocking Comforts features

### ISSUE THREAD

**Issue by poopkickercmyk** [GeheimagentNr1/EasierSleeping#1]
**Versions**
Minecraft Version: 1.16.5
Minecraft Forge Version: 1.16.5 (36.1.16)
Mod Version: 1.2.0

**Describe the bug**
In Comforts there is an item called the Hammock that can turn day to night. I think easier sleeping is blocking it

**To Reproduce**
Steps to reproduce the behaviour:
1. Sleep in hammock
2. the time turns to earlier the same day

**Expected behaviour**
it would turn afternoon

**Comment by GeheimagentNr1** [comment]
<table><tbody><tr><th>Status:</th><td>Implemented</td></tr><tr><th>Issue type:</th><td>Bug/Enhancement</td></tr><tr><th>Fix type:</th><td>New Feature</td></tr><tr><th>Fix version:</th><td>2.1.0</td></tr><tr><th>Fix release date:</th><td>05.08.2021</td></tr></tbody></table>

**Issue confirmed for:**

*   Minecraft version: 1.16.5  
    Mod version:  1.2.0

**TODOs:**

*   [x] Investigate in version 1.2.0
*   [x] Investigate in Minecraft version 1.16.5
*   [x] Testing with Morpheus Mod as comparison
*   [x] Deciding, if the issue will be fixed (because of notice 1.) and how.
    *   A possible solution could be a list of blocks, which will be ignored, if the player uses them to sleep. But that would be a new feature.
*    [x]  Implement a block blacklist, for bed being ignored by the sleep percentage.

#### Notices

1.  Morpheus has the same problem
